package persistencia;
// Generated 02/11/2016 21:54:38 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Valor generated by hbm2java
 */
@Entity
@Table(name = "valor", catalog = "prevCalc")
public class Valor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9082502496581677612L;
	
	private Integer idValores;
	private double dominio;
	private double contraDominio;

	public Valor() {
	}

	public Valor(double dominio, double contraDominio) {
		this.dominio = dominio;
		this.contraDominio = contraDominio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idValores", unique = true, nullable = false)
	public Integer getIdValores() {
		return this.idValores;
	}

	public void setIdValores(Integer idValores) {
		this.idValores = idValores;
	}

	@Column(name = "dominio", nullable = false, precision = 22, scale = 0)
	public double getDominio() {
		return this.dominio;
	}

	public void setDominio(double dominio) {
		this.dominio = dominio;
	}

	@Column(name = "contraDominio", nullable = false, precision = 22, scale = 0)
	public double getContraDominio() {
		return this.contraDominio;
	}

	public void setContraDominio(double contraDominio) {
		this.contraDominio = contraDominio;
	}

}
