-- MySQL Script generated by MySQL Workbench
-- 11/02/16 21:34:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prevCalc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prevCalc` DEFAULT CHARACTER SET utf8 ;
USE `prevCalc` ;

-- -----------------------------------------------------
-- Table `prevCalc`.`Valores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prevCalc`.`Valor` (
  `idValores` INT NOT NULL AUTO_INCREMENT,
  `dominio` DOUBLE NOT NULL,
  `contraDominio` DOUBLE NOT NULL,
  PRIMARY KEY (`idValores`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
